---
name: Release
on:
  push:
    tags:
      - "*"
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and package
        run: sudo -E bash .github/scripts/build-and-package.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /pkg/*.deb
